import { useEffect, useMemo, useRef, useState } from 'react';
import { Download, Images, Save } from 'lucide-react';
import { useProject, type VersionKey } from '../../project/ProjectContext';

const keys: VersionKey[]=['v1','v2','v3'];

function slug(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,60)||'headline'}
function download(url:string,name:string){const a=document.createElement('a');a.href=url;a.download=name;a.click()}
function roundRect(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number,fill:string){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fillStyle=fill;ctx.fill()}
function wrap(ctx:CanvasRenderingContext2D,text:string,maxWidth:number,maxLines=5){const words=text.split(/\s+/).filter(Boolean);const lines:string[]=[];let line='';for(const word of words){const next=line?`${line} ${word}`:word;if(ctx.measureText(next).width>maxWidth&&line){lines.push(line);line=word;if(lines.length>=maxLines)break}else line=next}if(lines.length<maxLines&&line)lines.push(line);return lines}

function drawHeadline(canvas:HTMLCanvasElement,lines:[string,string,string],style:'pressespiegel'|'pressepunkt',topic:string){const ctx=canvas.getContext('2d');if(!ctx)return;canvas.width=1080;canvas.height=1350;ctx.clearRect(0,0,1080,1350);if(style==='pressespiegel'){
  ctx.fillStyle='#f6f8fb';ctx.fillRect(0,0,1080,1350);ctx.fillStyle='#111827';ctx.fillRect(0,0,1080,110);ctx.fillStyle='#fff';ctx.font='800 34px Inter,Arial';ctx.fillText('PRESSespiegel',56,70);ctx.fillStyle='#e11d48';ctx.fillRect(56,190,150,12);ctx.fillStyle='#111827';ctx.font='800 48px Inter,Arial';wrap(ctx,lines[0],950,3).forEach((l,i)=>ctx.fillText(l,56,290+i*60));ctx.font='950 84px Inter,Arial';wrap(ctx,lines[1],950,5).forEach((l,i)=>ctx.fillText(l,56,510+i*96));ctx.fillStyle='#475569';ctx.font='700 45px Inter,Arial';wrap(ctx,lines[2],950,5).forEach((l,i)=>ctx.fillText(l,56,1010+i*56));ctx.fillStyle='#64748b';ctx.font='600 25px Inter,Arial';ctx.fillText(topic.slice(0,70),56,1285);
}else{
  ctx.fillStyle='#0f172a';ctx.fillRect(0,0,1080,1350);roundRect(ctx,52,72,976,1200,34,'#fff');ctx.fillStyle='#f97316';roundRect(ctx,90,120,300,58,12,'#f97316');ctx.fillStyle='#fff';ctx.font='900 28px Inter,Arial';ctx.fillText(topic.slice(0,28).toUpperCase(),112,160);ctx.fillStyle='#111827';ctx.font='800 46px Inter,Arial';wrap(ctx,lines[0],900,3).forEach((l,i)=>ctx.fillText(l,90,290+i*58));ctx.font='950 86px Inter,Arial';wrap(ctx,lines[1],900,5).forEach((l,i)=>ctx.fillText(l,90,500+i*98));ctx.fillStyle='#ea580c';ctx.font='800 43px Inter,Arial';wrap(ctx,lines[2],900,5).forEach((l,i)=>ctx.fillText(l,90,1010+i*54));ctx.fillStyle='#94a3b8';ctx.font='600 24px Inter,Arial';ctx.fillText(new Intl.DateTimeFormat('de-DE',{dateStyle:'long'}).format(new Date()),90,1210)
}}

function cardCanvas(version:VersionKey,header:string,description:string,excerpt:string,kind:'article'|'social',style:number){const canvas=document.createElement('canvas');canvas.width=1080;canvas.height=kind==='article'?1350:650;const ctx=canvas.getContext('2d')!;const palettes=kind==='article'?[['#f8f5ef','#171717','#a61f2d'],['#ffffff','#0d2745','#1684d8'],['#ffffff','#080808','#e51b23']]:[['#eef3f9','#132238','#1557b0'],['#0b111b','#f7f9fc','#64748b'],['#fdf2f8','#2d2036','#a855f7']];const [bg,fg,accent]=palettes[style];ctx.fillStyle=bg;ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle=accent;ctx.fillRect(0,0,canvas.width,kind==='article'?34:18);ctx.fillStyle=fg;ctx.font=`900 ${kind==='article'?70:48}px Inter,Arial`;wrap(ctx,header,900,kind==='article'?5:3).forEach((l,i)=>ctx.fillText(l,70,(kind==='article'?180:130)+i*(kind==='article'?82:58)));ctx.fillStyle=accent;ctx.fillRect(70,kind==='article'?620:330,220,8);ctx.fillStyle=fg;ctx.font=`650 ${kind==='article'?32:30}px Inter,Arial`;wrap(ctx,description,900,kind==='article'?5:4).forEach((l,i)=>ctx.fillText(l,70,(kind==='article'?700:390)+i*(kind==='article'?44:40)));if(kind==='article'){ctx.fillStyle='#64748b';ctx.font='400 27px Inter,Arial';wrap(ctx,excerpt,900,7).forEach((l,i)=>ctx.fillText(l,70,1010+i*38));ctx.font='700 20px Inter,Arial';ctx.fillText(`VERSION ${version.slice(1)} · ARTIKELAUSSCHNITT`,70,1300)}else{ctx.fillStyle='#94a3b8';ctx.font='700 22px Inter,Arial';ctx.fillText(`vor ${8+style*7} Minuten · Version ${version.slice(1)}`,70,590)}return canvas}

export function HeadlinePanel(){
  const {newsPackage,selectedVersion,setSelectedVersion,updateVersion,addAsset,settings,setSettings}=useProject();
  const canvasRef=useRef<HTMLCanvasElement>(null);const [status,setStatus]=useState('');
  const version=newsPackage?.versions[selectedVersion];
  const lines=useMemo<[string,string,string]>(()=>version?[version.triple_headline.line1,version.triple_headline.line2,version.triple_headline.line3]:['','',''],[version]);
  useEffect(()=>{if(canvasRef.current&&newsPackage)drawHeadline(canvasRef.current,lines,settings.headlineStyle,newsPackage.meta.topic)},[lines,settings.headlineStyle,newsPackage]);
  if(!newsPackage||!version)return <div className="empty-workspace"><h2>Kein Newspaket</h2><p>Importiere zuerst JSON.</p></div>;
  function setLine(index:number,value:string){const next:[string,string,string]=[...lines] as [string,string,string];next[index]=value;updateVersion(selectedVersion,{triple_headline:{line1:next[0],line2:next[1],line3:next[2]}})}
  function currentUrl(){return canvasRef.current?.toDataURL('image/png')||''}
  function saveCurrent(){const url=currentUrl();if(!url)return;addAsset({kind:'headline',name:`headline-${slug(lines[1]||version.header)}.png`,url,mimeType:'image/png',source:'headline-generator'});setStatus('Headline wurde in die Asset-Zentrale übernommen.')}
  function generateCards(kind:'article'|'social') {let count=0;for(const key of keys){const v=newsPackage!.versions[key];const description=String(v.description||'').replace(/(^|\s)#[\p{L}\p{N}_-]+/gu,' ').replace(/\s+/g,' ').trim();const excerpt=v.speech_text.split(/\s+/).slice(0,40).join(' ');for(let style=0;style<3;style++){const c=cardCanvas(key,v.header,description,excerpt,kind,style);const url=c.toDataURL('image/png');addAsset({kind:'headline',name:`${kind}-${slug(v.header)}-${key}-${style+1}.png`,url,mimeType:'image/png',source:`${kind}-generator`});count++}}setStatus(`${count} ${kind==='article'?'Artikelkarten':'Social-Cards'} erzeugt und in Assets abgelegt.`)}
  return <div className="module-stack"><div className="module-title-row"><div><h2>Schlagzeile</h2><p>Dreizeiler aus dem Newspaket – direkt als Produktionsgrafik.</p></div><div className="segmented"><button className={settings.headlineStyle==='pressespiegel'?'active':''} onClick={()=>setSettings({headlineStyle:'pressespiegel'})}>Pressespiegel</button><button className={settings.headlineStyle==='pressepunkt'?'active':''} onClick={()=>setSettings({headlineStyle:'pressepunkt'})}>Pressepunkt</button></div></div>
  <div className="version-tabs">{keys.map(key=><button className={selectedVersion===key?'active':''} onClick={()=>setSelectedVersion(key)} key={key}>Version {key.slice(1)}</button>)}</div>
  <div className="headline-workspace"><div className="headline-fields">{lines.map((line,i)=><label className="field" key={i}><span>Zeile {i+1}</span><textarea value={line} onChange={e=>setLine(i,e.target.value)}/></label>)}<div className="action-row"><button className="primary" onClick={saveCurrent}><Save size={16}/> Als Asset</button><button className="secondary" onClick={()=>download(currentUrl(),`headline-${slug(lines[1]||version.header)}.png`)}><Download size={16}/> PNG</button></div></div><div className="headline-preview"><canvas ref={canvasRef}/></div></div>
  <div className="subtool"><div><strong>Automatische Karten aus allen 3 Versionen</strong><span>Je Version werden drei Artikel- und drei Social-Designs erzeugt.</span></div><div className="action-row"><button className="secondary" onClick={()=>generateCards('article')}><Images size={16}/> 9 Artikelkarten</button><button className="secondary" onClick={()=>generateCards('social')}><Images size={16}/> 9 Social-Cards</button></div></div>
  {status&&<div className="notice success">{status}</div>}</div>
}
