import { useEffect, useRef, useState } from 'react';
import { FileJson, ImagePlus, Maximize2, Minimize2, Trash2, Upload, X } from 'lucide-react';
import type { AssetKind, NewsVersion, ProjectAsset, ProjectState, VersionKey } from '../domain/project';
import { availableVersionKeys, createVersionFlows, parsePackageJson, uid } from '../domain/project';
import { HeadlineWorkspace } from './HeadlineWorkspace';
import { ResearchWorkspace } from './ResearchWorkspace';
import { StudioWorkspace } from './StudioWorkspace';

type Props={moduleId:string;version?:VersionKey;project:ProjectState;setProject:React.Dispatch<React.SetStateAction<ProjectState>>;onClose:()=>void};
type SharedProps=Omit<Props,'moduleId'|'onClose'|'version'>;
type VersionProps=SharedProps&{version:VersionKey};

function Header({title,subtitle,onClose}:{title:string;subtitle:string;onClose:()=>void}){return <div className="workspace-head"><div><h2>{title}</h2><p>{subtitle}</p></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div>}
function Empty({text}:{text:string}){return <div className="empty-state">{text}</div>}

function JsonImport({project,setProject}:SharedProps){
  const [json,setJson]=useState('');const [state,setState]=useState('');const fileRef=useRef<HTMLInputElement>(null);
  const apply=(value=json)=>{try{const newsPackage=parsePackageJson(value);const versions=availableVersionKeys(newsPackage);const first=versions[0]||'v1';setProject(current=>({...current,newsPackage,activeVersion:first,versionFlows:createVersionFlows(newsPackage),workflowRevision:current.workflowRevision+1}));setState(`✓ ${newsPackage.meta.topic} · ${versions.length} Version${versions.length===1?'':'en'} · ${versions.length} Flow${versions.length===1?'':'s'} erstellt`)}catch(error){setState(error instanceof Error?error.message:String(error))}};
  return <div className="workspace-section"><div className="callout"><FileJson size={18}/><div><b>JSON ist der Projekteinstieg</b><span>Jede vorhandene Version erzeugt automatisch einen eigenen Produktionsstrang.</span></div></div><textarea className="json-editor" value={json} onChange={e=>setJson(e.target.value)} placeholder={'{\n  "package": {\n    "source_url": "https://…",\n    "meta": { "topic": "…", "breaking": false },\n    "versions": { "v1": {}, "v2": {}, "v3": {} }\n  }\n}'}/><div className="action-row"><button className="primary" onClick={()=>apply()}>JSON importieren</button><button onClick={()=>fileRef.current?.click()}><Upload size={15}/>Datei wählen</button></div><input ref={fileRef} hidden type="file" accept="application/json,.json" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;const value=await f.text();setJson(value);apply(value)}}/>{state&&<div className={`message ${state.startsWith('✓')?'ok':'error'}`}>{state}</div>}{project.newsPackage&&<div className="summary-card"><span>Aktuelles Paket</span><strong>{project.newsPackage.meta.topic}</strong><small>{availableVersionKeys(project.newsPackage).map(v=>v.toUpperCase()).join(' · ')}</small></div>}</div>
}

function NewspackageWorkspace({project,setProject,version}:VersionProps){
  const data=project.newsPackage?.versions[version];if(!data)return <Empty text={`${version.toUpperCase()} ist im Paket nicht vorhanden.`}/>;
  const patch=(next:Partial<NewsVersion>)=>setProject(current=>{const currentVersion=current.newsPackage?.versions[version];if(!current.newsPackage||!currentVersion)return current;return {...current,newsPackage:{...current.newsPackage,versions:{...current.newsPackage.versions,[version]:{...currentVersion,...next}}}}});
  const words=data.speech_text.trim().split(/\s+/).filter(Boolean).length;
  return <div className="workspace-section"><div className="version-context"><b>{version.toUpperCase()}</b><span>{data.header}</span></div><div className="field-grid"><label className="wide">Header<input value={data.header} onChange={e=>patch({header:e.target.value})}/></label><label className="wide">Sprechtext <span>{words} Wörter</span><textarea className="tall" value={data.speech_text} onChange={e=>patch({speech_text:e.target.value})}/></label><label className="wide">Beschreibung<textarea value={data.description} onChange={e=>patch({description:e.target.value})}/></label><label>Zeile 1<input value={data.triple_headline.line1} onChange={e=>patch({triple_headline:{...data.triple_headline,line1:e.target.value}})}/></label><label>Zeile 2<input value={data.triple_headline.line2} onChange={e=>patch({triple_headline:{...data.triple_headline,line2:e.target.value}})}/></label><label className="wide">Zeile 3<input value={data.triple_headline.line3} onChange={e=>patch({triple_headline:{...data.triple_headline,line3:e.target.value}})}/></label><label className="wide">Bildprompt<textarea value={data.image_prompt} onChange={e=>patch({image_prompt:e.target.value})}/></label><label className="wide">POV / Visual<textarea value={data.pov_visual.description} onChange={e=>patch({pov_visual:{...data.pov_visual,description:e.target.value}})}/></label><label className="wide">Hashtags<input value={data.hashtags.join(' ')} onChange={e=>patch({hashtags:e.target.value.split(/\s+/).filter(Boolean).slice(0,5)})}/></label></div></div>
}

function AssetsWorkspace({project,setProject}:SharedProps){
  const [filter,setFilter]=useState<'all'|AssetKind>('all');const [search,setSearch]=useState('');const file=useRef<HTMLInputElement>(null);const visible=project.assets.filter(asset=>(filter==='all'||asset.kind===filter)&&asset.name.toLowerCase().includes(search.toLowerCase()));
  const addFiles=(files:FileList|null)=>{if(!files)return;const next=[...files].map(f=>({id:uid('asset'),kind:(f.type.startsWith('video')?'video':f.type.startsWith('audio')?'audio':'image') as AssetKind,name:f.name,url:URL.createObjectURL(f),mime:f.type,size:f.size,source:'upload'}));setProject(current=>({...current,assets:[...next,...current.assets]}))};
  return <div className="workspace-section"><div className="callout shared-callout"><ImagePlus size={18}/><div><b>Gemeinsame Asset-Bibliothek</b><span>Alle Medien und erzeugten Headlines stehen automatisch jedem Versions-Studio zur Verfügung.</span></div></div><div className="asset-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Assets durchsuchen…"/><button onClick={()=>file.current?.click()}><ImagePlus size={16}/>Medien hinzufügen</button><input ref={file} hidden multiple type="file" accept="image/*,video/*,audio/*" onChange={e=>addFiles(e.target.files)}/></div><div className="filter-row">{(['all','image','video','headline','banner','audio','export'] as const).map(key=><button key={key} className={filter===key?'active':''} onClick={()=>setFilter(key)}>{key==='all'?'Alle':key}<span>{key==='all'?project.assets.length:project.assets.filter(a=>a.kind===key).length}</span></button>)}</div><div className="asset-grid">{visible.map(asset=><AssetCard key={asset.id} asset={asset} onDelete={()=>setProject(current=>({...current,assets:current.assets.filter(item=>item.id!==asset.id)}))}/>)}{!visible.length&&<Empty text="Noch keine passenden Assets vorhanden."/>}</div><label>Projekt-Notizen<textarea value={project.notes} onChange={e=>setProject(p=>({...p,notes:e.target.value}))} placeholder="Gemeinsame Hinweise für alle Versionen…"/></label></div>
}
function AssetCard({asset,onDelete}:{asset:ProjectAsset;onDelete:()=>void}){return <article className="asset-card"><div className="asset-media">{asset.kind==='video'?<video src={asset.url} muted/>:asset.kind==='audio'?<div className="audio-icon">♪</div>:<img src={asset.url} alt=""/>}<span>{asset.version?`${asset.kind} · ${asset.version.toUpperCase()}`:asset.kind}</span><button onClick={onDelete}><Trash2 size={13}/></button></div><b>{asset.name}</b><small>{asset.size?`${(asset.size/1048576).toFixed(1)} MB`:asset.source}</small></article>}

function Img2VidWorkspace({project,setProject}:SharedProps){const images=project.assets.filter(a=>['image','headline','banner'].includes(a.kind));const [asset,setAsset]=useState('');const [model,setModel]=useState('bytedance/seedance-1-pro');const [prompt,setPrompt]=useState('Create a realistic video from this image while preserving the original frame exactly. Keep the camera locked off and static. Do not add new objects. Allow only subtle environmental motion.');const chosen=images.find(a=>a.id===asset);return <div className="workspace-section"><div className="callout"><b>Optionales Werkzeug</b><span>Img2Vid erzeugt zusätzliche gemeinsame Assets und gehört nicht zu einem Versions-Flow.</span></div><label>Startbild<select value={asset} onChange={e=>setAsset(e.target.value)}><option value="">Asset wählen…</option>{images.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label>{chosen&&<img className="img2vid-preview" src={chosen.url} alt=""/>}<label>Videomodell<select value={model} onChange={e=>setModel(e.target.value)}><option value="bytedance/seedance-1-pro">Seedance 1 Pro</option><option value="wan-video/wan-2.2-i2v-fast">Wan 2.2 Fast</option><option value="kwaivgi/kling-v2.1">Kling v2.1</option></select></label><label>Prompt<textarea className="tall" value={prompt} onChange={e=>setPrompt(e.target.value)}/></label><button disabled={!chosen} className="primary full" onClick={()=>setProject(p=>({...p,notes:`${p.notes}\nImg2Vid vorbereitet: ${model} · ${chosen?.name||''}`.trim()}))}>Job vorbereiten</button></div>}

function StudioOverlay({project,setProject,version,onClose}:VersionProps&{onClose:()=>void}){
  const shellRef=useRef<HTMLDivElement>(null);
  const [browserFullscreen,setBrowserFullscreen]=useState(false);
  const data=project.newsPackage?.versions[version];
  useEffect(()=>{const change=()=>setBrowserFullscreen(Boolean(document.fullscreenElement));document.addEventListener('fullscreenchange',change);return()=>document.removeEventListener('fullscreenchange',change)},[]);
  useEffect(()=>()=>{if(document.fullscreenElement)void document.exitFullscreen().catch(()=>{})},[]);
  const toggleFullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(shellRef.current?.requestFullscreen)await shellRef.current.requestFullscreen()}catch{/* browser may deny fullscreen outside a user gesture */}};
  return <div ref={shellRef} className="studio-workspace-overlay">
    <header className="studio-workspace-header"><div className="studio-workspace-title"><span className="studio-version-badge">{version.toUpperCase()}</span><div><h2>Studio {version.toUpperCase()}</h2><p>{data?.header||'Interaktive 9:16-Produktion'}</p></div></div><div className="studio-workspace-header-actions"><button onClick={()=>void toggleFullscreen()}>{browserFullscreen?<Minimize2 size={16}/>:<Maximize2 size={16}/>}<span>{browserFullscreen?'Vollbild verlassen':'Vollbild'}</span></button><button className="studio-close" onClick={onClose}><X size={18}/><span>Schließen</span></button></div></header>
    <div className="studio-workspace-body"><StudioWorkspace project={project} setProject={setProject} version={version}/></div>
  </div>;
}

export function ModuleWorkspace({moduleId,version,project,setProject,onClose}:Props){
  if(moduleId==='studio'&&version)return <StudioOverlay project={project} setProject={setProject} version={version} onClose={onClose}/>;
  let title='Modul',subtitle='';let body:React.ReactNode=<Empty text="Für dieses Modul ist keine Arbeitsfläche definiert."/>;
  if(moduleId==='json-input'){title='JSON Input';subtitle='Exportiertes Datenpaket importieren und Versions-Flows erzeugen.';body=<JsonImport project={project} setProject={setProject}/>}
  else if(moduleId==='news-package'&&version){title=`Newspaket ${version.toUpperCase()}`;subtitle=project.newsPackage?.versions[version]?.header||'Paketdaten dieses Versionsstrangs bearbeiten.';body=<NewspackageWorkspace project={project} setProject={setProject} version={version}/>}
  else if(moduleId==='headline'&&version){title=`Schlagzeile ${version.toUpperCase()}`;subtitle='Original-Schlagzeilengenerator inklusive Zeitungsausschnitten.';body=<HeadlineWorkspace project={project} setProject={setProject} version={version}/>}
  else if(moduleId==='research'){title='Recherche';subtitle='Optionales globales Recherche-Werkzeug für alle Flows.';body=<ResearchWorkspace project={project}/>}
  else if(moduleId==='assets'){title='Assets';subtitle='Gemeinsame Medienbibliothek aller Versions-Flows.';body=<AssetsWorkspace project={project} setProject={setProject}/>}
  else if(moduleId==='img2vid'){title='Img2Vid';subtitle='Optionaler Erzeuger zusätzlicher gemeinsamer Video-Assets.';body=<Img2VidWorkspace project={project} setProject={setProject}/>}
  return <aside className="workspace"><Header title={title} subtitle={subtitle} onClose={onClose}/><div className="workspace-body">{body}</div></aside>;
}
