import { useEffect, useMemo, useRef, useState } from 'react';
import { Copy, Download, Pause, Play, Plus, RotateCcw, Trash2, X } from 'lucide-react';
import type { ClipAnimation, ClipTemplate, ProjectAsset, ProjectState, TimelineClip, TimelineLane, VersionKey } from '../domain/project';
import { uid } from '../domain/project';

type Props={project:ProjectState;setProject:React.Dispatch<React.SetStateAction<ProjectState>>;version:VersionKey};
const W=1080,H=1920;
const laneLabels:Record<TimelineLane,string>={banner:'Banner',main:'Main',wan:'B-Roll',headline:'Headline',text:'Text',sound:'Sound'};
const lanes:TimelineLane[]=['banner','main','wan','headline','text','sound'];
const animations:ClipAnimation[]=['news','left','right','punch','drop','fade','none'];
const templates:ClipTemplate[]=['broll','split','story'];

function formatTime(value:number){const m=Math.floor(value/60),s=Math.floor(value%60);return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function clamp(v:number,min:number,max:number){return Math.max(min,Math.min(max,v))}
function compatible(asset:ProjectAsset,lane:TimelineLane){if(lane==='sound')return asset.kind==='audio';if(lane==='main')return asset.kind==='video'||asset.kind==='image';if(lane==='headline')return ['headline','image'].includes(asset.kind);if(lane==='banner')return ['banner','image'].includes(asset.kind);if(lane==='wan')return ['video','image','headline','banner'].includes(asset.kind);return false}
function isImage(asset?:ProjectAsset){return !!asset&&!['video','audio','export'].includes(asset.kind)}
function animationLabel(v:ClipAnimation){return ({news:'News-Swoop',left:'Spin links',right:'Spin rechts',punch:'Pop & Zoom',drop:'Drop & Swing',fade:'Sanft',none:'Keine'} as const)[v]}

export function StudioWorkspace({project,setProject,version}:Props){
  const canvasRef=useRef<HTMLCanvasElement>(null);
  const mediaRef=useRef(new Map<string,HTMLImageElement|HTMLVideoElement|HTMLAudioElement>());
  const dragRef=useRef<{id:string;mode:'move'|'left'|'right';x:number;start:number;duration:number}|null>(null);
  const rafRef=useRef(0);
  const [selected,setSelected]=useState('');
  const [time,setTime]=useState(0);
  const [playing,setPlaying]=useState(false);
  const [zoom,setZoom]=useState(1);
  const [pickerLane,setPickerLane]=useState<TimelineLane|null>(null);
  const [exporting,setExporting]=useState(false);
  const [message,setMessage]=useState('');
  const clips=project.versionFlows[version]?.timeline||[];
  const duration=Math.max(20,...clips.map(c=>c.start+c.duration));
  const selectedClip=clips.find(c=>c.id===selected);
  const pxPerSec=30*zoom;
  const timelineWidth=Math.max(760,duration*pxPerSec);

  const setTimeline=(fn:(items:TimelineClip[])=>TimelineClip[])=>setProject(p=>({...p,versionFlows:{...p.versionFlows,[version]:{timeline:fn(p.versionFlows[version]?.timeline||[])}}}));
  const patch=(id:string,next:Partial<TimelineClip>)=>setTimeline(items=>items.map(c=>c.id===id?{...c,...next}:c));
  const remove=(id:string)=>{setTimeline(items=>items.filter(c=>c.id!==id));if(selected===id)setSelected('')};
  const duplicate=(clip:TimelineClip)=>{const copy={...clip,id:uid('clip'),label:`${clip.label} Kopie`,start:Math.min(duration,clip.start+Math.min(1,clip.duration/4))};setTimeline(items=>[...items,copy]);setSelected(copy.id)};
  const nextStart=(lane:TimelineLane)=>Math.max(0,...clips.filter(c=>c.lane===lane).map(c=>c.start+c.duration));
  const defaultDuration=(lane:TimelineLane,asset?:ProjectAsset)=>lane==='headline'||lane==='banner'?4:lane==='wan'&&isImage(asset)?5:lane==='sound'?15:10;
  const addClip=(lane:TimelineLane,asset?:ProjectAsset)=>{if(lane==='text'){const c:TimelineClip={id:uid('text'),lane,label:'Textfeld',text:'Textfeld',start:nextStart(lane),duration:6,animation:'fade',x:540,y:1500,scale:1};setTimeline(v=>[...v,c]);setSelected(c.id);setPickerLane(null);return}if(!asset||!compatible(asset,lane))return;const c:TimelineClip={id:uid('clip'),lane,assetId:asset.id,label:asset.name,start:nextStart(lane),duration:defaultDuration(lane,asset),template:lane==='wan'?'broll':undefined,animation:lane==='headline'||lane==='banner'?'news':undefined,caption:asset.caption||'',scale:1,rotation:0,volume:1};setTimeline(v=>[...v,c]);setSelected(c.id);setPickerLane(null);void probeDuration(asset).then(d=>{if(d>0&&['main','wan','sound'].includes(lane))patch(c.id,{duration:Math.min(d,60)})})};

  async function probeDuration(asset:ProjectAsset){if(!['video','audio'].includes(asset.kind))return 0;return new Promise<number>(resolve=>{const el=document.createElement(asset.kind==='video'?'video':'audio');el.preload='metadata';el.src=asset.url;el.onloadedmetadata=()=>resolve(Number.isFinite(el.duration)?el.duration:0);el.onerror=()=>resolve(0)})}
  function ensureMedia(asset:ProjectAsset){const cached=mediaRef.current.get(asset.id);if(cached)return cached;if(asset.kind==='video'){const v=document.createElement('video');v.src=asset.url;v.muted=true;v.playsInline=true;v.preload='auto';mediaRef.current.set(asset.id,v);return v}if(asset.kind==='audio'){const a=new Audio(asset.url);a.preload='auto';mediaRef.current.set(asset.id,a);return a}const img=new Image();img.src=asset.url;mediaRef.current.set(asset.id,img);return img}

  const assetMap=useMemo(()=>new Map(project.assets.map(a=>[a.id,a])),[project.assets]);
  useEffect(()=>{project.assets.forEach(ensureMedia)},[project.assets]);

  function active(lane:TimelineLane,t:number){return clips.filter(c=>c.lane===lane&&t>=c.start&&t<c.start+c.duration).sort((a,b)=>a.start-b.start).at(-1)}
  function drawCover(ctx:CanvasRenderingContext2D,media:CanvasImageSource,x:number,y:number,w:number,h:number,scale=1){const mw=(media as HTMLImageElement).naturalWidth||(media as HTMLVideoElement).videoWidth||w,mh=(media as HTMLImageElement).naturalHeight||(media as HTMLVideoElement).videoHeight||h;const r=Math.max(w/mw,h/mh)*scale,dw=mw*r,dh=mh*r;ctx.drawImage(media,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
  function drawContain(ctx:CanvasRenderingContext2D,media:CanvasImageSource,x:number,y:number,w:number,h:number,scale=1,rotation=0,alpha=1){const mw=(media as HTMLImageElement).naturalWidth||(media as HTMLVideoElement).videoWidth||w,mh=(media as HTMLImageElement).naturalHeight||(media as HTMLVideoElement).videoHeight||h;const r=Math.min(w/mw,h/mh)*scale,dw=mw*r,dh=mh*r;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x+w/2,y+h/2);ctx.rotate(rotation*Math.PI/180);ctx.drawImage(media,-dw/2,-dh/2,dw,dh);ctx.restore()}
  function anim(clip:TimelineClip,t:number){const local=(t-clip.start)/Math.min(.6,Math.max(.2,clip.duration*.18)),p=clamp(local,0,1);let alpha=1,scale=clip.scale||1,rotation=clip.rotation||0,dx=0,dy=0;if(clip.animation==='fade')alpha=p;if(clip.animation==='news'){dx=(1-p)*180;scale*=.82+.18*p}if(clip.animation==='left')rotation+=-16*(1-p);if(clip.animation==='right')rotation+=16*(1-p);if(clip.animation==='punch')scale*=.72+.28*p;if(clip.animation==='drop')dy=-220*(1-p);return{alpha,scale,rotation,dx,dy}}
  function syncVideo(asset:ProjectAsset,clip:TimelineClip,t:number){const media=ensureMedia(asset);if(media instanceof HTMLVideoElement){const local=clamp(t-clip.start,0,Math.max(0,media.duration||clip.duration));if(Math.abs(media.currentTime-local)>.12)try{media.currentTime=local}catch{}return media}return media}
  function renderFrame(t:number){const c=canvasRef.current;if(!c)return;const ctx=c.getContext('2d');if(!ctx)return;ctx.clearRect(0,0,W,H);ctx.fillStyle='#070a10';ctx.fillRect(0,0,W,H);
    const main=active('main',t);if(main?.assetId){const a=assetMap.get(main.assetId);if(a){const m=syncVideo(a,main,t);if((m instanceof HTMLImageElement&&m.complete)||(m instanceof HTMLVideoElement&&m.readyState>=2))drawCover(ctx,m,0,0,W,H,main.scale||1)}}
    const wan=active('wan',t);if(wan?.assetId){const a=assetMap.get(wan.assetId);if(a){const m=syncVideo(a,wan,t);if((m instanceof HTMLImageElement&&m.complete)||(m instanceof HTMLVideoElement&&m.readyState>=2)){const tpl=wan.template||'broll';if(tpl==='broll')drawCover(ctx,m,0,0,W,H,wan.scale||1);else if(tpl==='split'){ctx.save();ctx.beginPath();ctx.rect(0,H/2,W,H/2);ctx.clip();drawCover(ctx,m,0,H/2,W,H/2,wan.scale||1);ctx.restore()}else{ctx.save();roundPath(ctx,90,360,900,1120,42);ctx.clip();drawCover(ctx,m,90,360,900,1120,wan.scale||1);ctx.restore();ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=8;roundPath(ctx,90,360,900,1120,42);ctx.stroke()}if(wan.caption){ctx.fillStyle='rgba(0,0,0,.72)';ctx.fillRect(0,H-150,W,150);ctx.fillStyle='#fff';ctx.font='700 42px Arial';ctx.textAlign='center';ctx.fillText(wan.caption,W/2,H-62)}}}
    const headline=active('headline',t);if(headline?.assetId){const a=assetMap.get(headline.assetId);if(a){const m=ensureMedia(a);if(m instanceof HTMLImageElement&&m.complete){const e=anim(headline,t);drawContain(ctx,m,50+e.dx,300+e.dy,980,1180,e.scale,e.rotation,e.alpha)}}}
    const banner=active('banner',t);if(banner?.assetId){const a=assetMap.get(banner.assetId);if(a){const m=ensureMedia(a);if(m instanceof HTMLImageElement&&m.complete){const e=anim(banner,t);drawContain(ctx,m,60+e.dx,80+e.dy,960,420,e.scale,e.rotation,e.alpha)}}}
    const text=active('text',t);if(text?.text){const e=anim(text,t);ctx.save();ctx.globalAlpha=e.alpha;ctx.fillStyle='rgba(0,0,0,.58)';ctx.textAlign='center';ctx.font=`900 ${Math.round(58*(text.scale||1))}px Arial`;const lines=wrapCanvas(ctx,text.text,920);const h=lines.length*70+36;ctx.fillRect(50,(text.y||1500)-h/2,980,h);ctx.fillStyle='#fff';lines.forEach((line,i)=>ctx.fillText(line,text.x||540,(text.y||1500)-((lines.length-1)*35)+i*70));ctx.restore()}
    if(!main&&!wan&&!headline&&!banner&&!text){ctx.fillStyle='#94a3b8';ctx.font='700 42px Arial';ctx.textAlign='center';ctx.fillText(`${version.toUpperCase()} · Timeline ist leer`,W/2,H/2)}
  }
  function roundPath(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
  function wrapCanvas(ctx:CanvasRenderingContext2D,text:string,max:number){const words=text.split(/\s+/),lines:string[]=[];let line='';for(const w of words){const t=line?`${line} ${w}`:w;if(ctx.measureText(t).width>max&&line){lines.push(line);line=w}else line=t}if(line)lines.push(line);return lines.slice(0,5)}

  useEffect(()=>{renderFrame(time)},[time,clips,project.assets]);
  useEffect(()=>{if(!playing){cancelAnimationFrame(rafRef.current);return}const base=performance.now()-time*1000;const tick=(now:number)=>{const next=(now-base)/1000;if(next>=duration){setTime(duration);setPlaying(false);return}setTime(next);rafRef.current=requestAnimationFrame(tick)};rafRef.current=requestAnimationFrame(tick);return()=>cancelAnimationFrame(rafRef.current)},[playing,duration]);
  useEffect(()=>{const sounds=clips.filter(c=>c.lane==='sound'&&c.assetId);for(const c of sounds){const a=assetMap.get(c.assetId!);if(!a)continue;const media=ensureMedia(a);if(!(media instanceof HTMLAudioElement))continue;const isActive=time>=c.start&&time<c.start+c.duration;if(playing&&isActive){media.volume=clamp(c.volume??1,0,1);const local=time-c.start;if(Math.abs(media.currentTime-local)>.4)media.currentTime=local;void media.play().catch(()=>{})}else media.pause()}return()=>{sounds.forEach(c=>{const a=c.assetId&&assetMap.get(c.assetId);const m=a&&mediaRef.current.get(a.id);if(m instanceof HTMLAudioElement)m.pause()})}},[time,playing,clips,assetMap]);

  useEffect(()=>{const move=(e:PointerEvent)=>{const d=dragRef.current;if(!d)return;const delta=(e.clientX-d.x)/pxPerSec;if(d.mode==='move')patch(d.id,{start:Math.max(0,d.start+delta)});else if(d.mode==='left'){const end=d.start+d.duration,next=Math.min(end-.5,Math.max(0,d.start+delta));patch(d.id,{start:next,duration:end-next})}else patch(d.id,{duration:Math.max(.5,d.duration+delta)})};const up=()=>{dragRef.current=null};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[pxPerSec]);

  const selectAndTime=(clip:TimelineClip)=>{setSelected(clip.id);setTime(clip.start)};
  const startDrag=(e:React.PointerEvent,clip:TimelineClip,mode:'move'|'left'|'right')=>{e.preventDefault();e.stopPropagation();setSelected(clip.id);dragRef.current={id:clip.id,mode,x:e.clientX,start:clip.start,duration:clip.duration}};

  async function exportVideo(){if(exporting)return;setExporting(true);setMessage('Export läuft in Echtzeit …');setPlaying(false);setTime(0);const canvas=canvasRef.current;if(!canvas){setExporting(false);return}const stream=canvas.captureStream(30);const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';const recorder=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:8_000_000});const chunks:Blob[]=[];recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const done=new Promise<void>(resolve=>{recorder.onstop=()=>resolve()});recorder.start(250);const start=performance.now();await new Promise<void>(resolve=>{const tick=(now:number)=>{const t=Math.min(duration,(now-start)/1000);setTime(t);renderFrame(t);if(t>=duration){resolve();return}requestAnimationFrame(tick)};requestAnimationFrame(tick)});recorder.stop();await done;const blob=new Blob(chunks,{type:'video/webm'});const url=URL.createObjectURL(blob);const name=`studio-${version}-${Date.now()}.webm`;setProject(p=>({...p,assets:[{id:uid('export'),kind:'export',name,url,mime:'video/webm',size:blob.size,source:'studio-export',version},...p.assets]}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setMessage('Export fertig und als gemeinsames Asset gespeichert.');setExporting(false)}

  return <div className="studio-v2">
    <div className="studio-topbar"><div className="version-context"><b>{version.toUpperCase()}</b><span>Eigene Timeline · gemeinsame Assets</span></div><div className="studio-actions"><button onClick={()=>{setTime(0);setPlaying(false)}}><RotateCcw size={15}/>Zurück</button><button className="primary" disabled={exporting||!clips.length} onClick={()=>void exportVideo()}><Download size={15}/>{exporting?'Export …':'Export'}</button></div></div>
    <div className="studio-grid">
      <div className="studio-preview-panel"><div className="studio-phone"><canvas ref={canvasRef} width={W} height={H}/><button className="preview-play" onClick={()=>setPlaying(v=>!v)}>{playing?<Pause size={22}/>:<Play size={22}/>}</button><span className="preview-time">{formatTime(time)} / {formatTime(duration)}</span></div>{message&&<div className="studio-message">{message}</div>}</div>
      <div className="studio-shared-assets"><div className="studio-panel-head"><div><b>Gemeinsame Assets</b><small>Drag & Drop auf eine Spur oder anklicken</small></div></div><div className="studio-asset-grid">{project.assets.filter(a=>a.kind!=='export').map(asset=><button key={asset.id} draggable onDragStart={e=>{e.dataTransfer.setData('application/asset',asset.id);e.dataTransfer.effectAllowed='copy'}} title={asset.name} onDoubleClick={()=>{const target:TimelineLane=asset.kind==='audio'?'sound':asset.kind==='headline'?'headline':asset.kind==='banner'?'banner':asset.kind==='video'?'wan':'wan';addClip(target,asset)}}>{asset.kind==='video'?<video src={asset.url} muted/>:asset.kind==='audio'?<span className="asset-audio">♪</span>:<img src={asset.url} alt=""/>}<strong>{asset.name}</strong></button>)}</div></div>
    </div>

    <div className="timeline-editor">
      <div className="timeline-toolbar"><div><button onClick={()=>setZoom(z=>clamp(z-.25,.5,3))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>clamp(z+.25,.5,3))}>+</button></div><span>{formatTime(time)} / {formatTime(duration)}</span></div>
      <div className="timeline-scroll"><div className="timeline-content" style={{width:timelineWidth}} onPointerDown={e=>{const rect=(e.currentTarget as HTMLDivElement).getBoundingClientRect();setTime(clamp((e.clientX-rect.left)/pxPerSec,0,duration))}}>
        <div className="timeline-ruler">{Array.from({length:Math.ceil(duration/5)+1},(_,i)=>i*5).map(t=><span key={t} style={{left:t*pxPerSec}}>{t}s</span>)}</div>
        <div className="timeline-playhead" style={{left:time*pxPerSec}}/>
        {lanes.map(lane=><div className="studio-lane" key={lane}><div className="studio-lane-label"><button onClick={()=>setPickerLane(lane)}><Plus size={13}/></button>{laneLabels[lane]}</div><div className="studio-lane-track" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('application/asset');const asset=project.assets.find(a=>a.id===id);if(asset)addClip(lane,asset)}}>{clips.filter(c=>c.lane===lane).map(clip=>{const asset=clip.assetId&&assetMap.get(clip.assetId);return <div key={clip.id} className={`studio-clip lane-${lane} ${selected===clip.id?'selected':''}`} style={{left:clip.start*pxPerSec,width:Math.max(24,clip.duration*pxPerSec)}} onPointerDown={e=>startDrag(e,clip,'move')} onClick={e=>{e.stopPropagation();selectAndTime(clip)}}>{asset&&isImage(asset)&&<span className="clip-thumb" style={{backgroundImage:`url(${asset.url})`}}/>}<span className="resize-handle left" onPointerDown={e=>startDrag(e,clip,'left')}/><b>{clip.label}</b><span className="resize-handle right" onPointerDown={e=>startDrag(e,clip,'right')}/></div>})}</div></div>)}
      </div></div>
    </div>

    {selectedClip&&<div className="clip-inspector"><div className="clip-inspector-head"><div><span>{laneLabels[selectedClip.lane]}</span><b>{selectedClip.label}</b></div><div><button title="Duplizieren" onClick={()=>duplicate(selectedClip)}><Copy size={15}/></button><button className="danger" title="Löschen" onClick={()=>remove(selectedClip.id)}><Trash2 size={15}/></button></div></div><div className="clip-fields"><label>Start<input type="number" min={0} step={.1} value={selectedClip.start.toFixed(1)} onChange={e=>patch(selectedClip.id,{start:Math.max(0,Number(e.target.value))})}/></label><label>Dauer<input type="number" min={.5} step={.1} value={selectedClip.duration.toFixed(1)} onChange={e=>patch(selectedClip.id,{duration:Math.max(.5,Number(e.target.value))})}/></label>{selectedClip.lane==='wan'&&<label>Fokus<select value={selectedClip.template||'broll'} onChange={e=>patch(selectedClip.id,{template:e.target.value as ClipTemplate})}>{templates.map(v=><option key={v} value={v}>{v==='broll'?'B-Roll Vollbild':v==='split'?'Split Fokus':'Story Window'}</option>)}</select></label>}{['headline','banner','text'].includes(selectedClip.lane)&&<label>Animation<select value={selectedClip.animation||'none'} onChange={e=>patch(selectedClip.id,{animation:e.target.value as ClipAnimation})}>{animations.map(v=><option key={v} value={v}>{animationLabel(v)}</option>)}</select></label>}{selectedClip.lane==='wan'&&<label className="wide">Caption<input value={selectedClip.caption||''} onChange={e=>patch(selectedClip.id,{caption:e.target.value})} placeholder="z. B. Ähnliche Abbildung / KI generiert"/></label>}{selectedClip.lane==='text'&&<label className="wide">Text<input value={selectedClip.text||''} onChange={e=>patch(selectedClip.id,{text:e.target.value})}/></label>}{['main','wan','headline','banner','text'].includes(selectedClip.lane)&&<><label>Skalierung<input type="number" min={.2} max={5} step={.1} value={selectedClip.scale||1} onChange={e=>patch(selectedClip.id,{scale:clamp(Number(e.target.value)||1,.2,5)})}/></label><label>Drehung<input type="number" min={-180} max={180} step={1} value={selectedClip.rotation||0} onChange={e=>patch(selectedClip.id,{rotation:Number(e.target.value)||0})}/></label></>}{selectedClip.lane==='sound'&&<label>Lautstärke<input type="range" min={0} max={1} step={.05} value={selectedClip.volume??1} onChange={e=>patch(selectedClip.id,{volume:Number(e.target.value)})}/></label>}</div></div>}

    {pickerLane&&<div className="studio-modal-backdrop" onClick={()=>setPickerLane(null)}><div className="studio-modal" onClick={e=>e.stopPropagation()}><div className="studio-modal-head"><div><b>{laneLabels[pickerLane]} hinzufügen</b><small>Gemeinsame Assets dieses Projekts</small></div><button onClick={()=>setPickerLane(null)}><X size={17}/></button></div>{pickerLane==='text'&&<button className="primary full" onClick={()=>addClip('text')}>Neues Textfeld</button>}<div className="picker-assets">{project.assets.filter(a=>compatible(a,pickerLane)).map(asset=><button key={asset.id} onClick={()=>addClip(pickerLane,asset)}>{asset.kind==='video'?<video src={asset.url} muted/>:asset.kind==='audio'?<span className="asset-audio">♪</span>:<img src={asset.url} alt=""/>}<strong>{asset.name}</strong></button>)}</div>{pickerLane!=='text'&&!project.assets.some(a=>compatible(a,pickerLane))&&<div className="empty-state">Kein passendes gemeinsames Asset vorhanden.</div>}</div></div>}
  </div>;
}
