import { useEffect, useMemo, useRef, useState } from 'react';
import type { PointerEvent as ReactPointerEvent } from 'react';
import { Download, Pause, Play, Plus, RotateCcw, X } from 'lucide-react';
import type { ClipAnimation, ClipTemplate, ProjectAsset, ProjectState, SlideshowMotion, TextAlign, TextStyle, TimelineClip, TimelineLane, VersionKey } from '../domain/project';
import { availableVersionKeys, uid } from '../domain/project';

type Props={project:ProjectState;setProject:React.Dispatch<React.SetStateAction<ProjectState>>;version:VersionKey};
const W=1080,H=1920;
const lanes:TimelineLane[]=['banner','main','wan','headline','text','sound'];
const laneLabels:Record<TimelineLane,string>={banner:'Banner',main:'Main',wan:'B-Roll',headline:'Headline',text:'Text',sound:'Sound'};
const animationLabels:Record<ClipAnimation,string>={news:'News-Swoop',left:'Spin links',right:'Spin rechts',punch:'Pop & Zoom',drop:'Drop & Swing',fade:'Sanft',none:'Keine'};
const motions:SlideshowMotion[]=['news','hard','soft','none'];
const motionLabels:Record<SlideshowMotion,string>={news:'News',hard:'Dynamisch',soft:'Sanft',none:'Statisch'};
const clamp=(v:number,min:number,max:number)=>Math.max(min,Math.min(max,v));
const fmt=(v:number)=>`${String(Math.floor(v/60)).padStart(2,'0')}:${String(Math.floor(v%60)).padStart(2,'0')}`;
const imageLike=(a:ProjectAsset)=>!['video','audio','export'].includes(a.kind);
const compatible=(a:ProjectAsset,lane:TimelineLane)=>lane==='sound'?a.kind==='audio':lane==='main'?['video','image'].includes(a.kind):lane==='wan'?['video','image','headline','banner'].includes(a.kind):lane==='headline'?['headline','image'].includes(a.kind):lane==='banner'?['banner','image'].includes(a.kind):false;
function shuffled<T>(items:T[]){const out=[...items];for(let i=out.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[out[i],out[j]]=[out[j],out[i]]}return out}
function newsSequence(ids:string[]){if(!ids.length)return[];const out:string[]=[];let last='';for(let round=0;round<10;round++){let order=shuffled(ids);if(order.length>1&&order[0]===last)order=[...order.slice(1),order[0]];out.push(...order);last=order.at(-1)||''}return out}
function wrap(ctx:CanvasRenderingContext2D,text:string,max:number){const words=text.split(/\s+/).filter(Boolean),lines:string[]=[];let line='';for(const word of words){const test=line?`${line} ${word}`:word;if(line&&ctx.measureText(test).width>max){lines.push(line);line=word}else line=test}if(line)lines.push(line);return lines.slice(0,5)}

export function StudioWorkspace({project,setProject,version}:Props){
  const canvasRef=useRef<HTMLCanvasElement>(null);
  const assetStripRef=useRef<HTMLDivElement>(null);
  const dragRef=useRef<{id:string;mode:'move'|'left'|'right';x:number;start:number;duration:number}|null>(null);
  const mediaRef=useRef(new Map<string,HTMLImageElement|HTMLVideoElement|HTMLAudioElement>());
  const rafRef=useRef(0);
  const [selected,setSelected]=useState('');
  const [time,setTime]=useState(0);
  const [playing,setPlaying]=useState(false);
  const [zoom,setZoom]=useState(1);
  const [pickerLane,setPickerLane]=useState<TimelineLane|null>(null);
  const [replaceId,setReplaceId]=useState('');
  const [slideSelection,setSlideSelection]=useState<Set<string>>(new Set());
  const [slideDuration,setSlideDuration]=useState(80);
  const [imageDuration,setImageDuration]=useState(3.2);
  const [slideMotion,setSlideMotion]=useState<SlideshowMotion>('news');
  const [textModal,setTextModal]=useState(false);
  const [textSource,setTextSource]=useState<VersionKey>(version);
  const [textValue,setTextValue]=useState(project.newsPackage?.versions[version]?.header||'');
  const [textStyle,setTextStyle]=useState<TextStyle>('redwhite');
  const [textAlign,setTextAlign]=useState<TextAlign>('center');
  const [menuPopover,setMenuPopover]=useState<'focus'|'animation'|''>('');
  const [exporting,setExporting]=useState(false);
  const [message,setMessage]=useState('');

  const clips=project.versionFlows[version]?.timeline||[];
  const duration=Math.max(20,...clips.map(c=>c.start+c.duration));
  const selectedClip=clips.find(c=>c.id===selected);
  const assets=project.assets.filter(a=>a.kind!=='export'&&(!a.version||a.version===version));
  const assetMap=useMemo(()=>new Map(project.assets.map(a=>[a.id,a])),[project.assets]);
  const pxPerSec=32*zoom;
  const timelineWidth=Math.max(900,duration*pxPerSec+86);
  const versions=availableVersionKeys(project.newsPackage);

  const setTimeline=(fn:(items:TimelineClip[])=>TimelineClip[])=>setProject(cur=>({...cur,versionFlows:{...cur.versionFlows,[version]:{...cur.versionFlows[version],timeline:fn(cur.versionFlows[version]?.timeline||[])}}}));
  const patch=(id:string,next:Partial<TimelineClip>)=>setTimeline(items=>items.map(c=>c.id===id?{...c,...next}:c));
  const remove=(id:string)=>{setTimeline(items=>items.filter(c=>c.id!==id));if(selected===id)setSelected('')};
  const nextStart=(lane:TimelineLane)=>Math.max(0,...clips.filter(c=>c.lane===lane).map(c=>c.start+c.duration));
  const duplicate=(clip:TimelineClip)=>{const copy={...clip,id:uid('clip'),label:`${clip.label} Kopie`,start:clip.start+Math.min(.8,clip.duration/4)};setTimeline(items=>[...items,copy]);setSelected(copy.id)};
  async function probe(asset:ProjectAsset){if(!['video','audio'].includes(asset.kind))return 0;return new Promise<number>(resolve=>{const el=document.createElement(asset.kind==='video'?'video':'audio');el.preload='metadata';el.src=asset.url;el.onloadedmetadata=()=>resolve(Number.isFinite(el.duration)?el.duration:0);el.onerror=()=>resolve(0)})}
  function addAsset(lane:TimelineLane,asset?:ProjectAsset,replaceClipId=''){
    if(!asset||!compatible(asset,lane))return;
    if(replaceClipId){patch(replaceClipId,{assetId:asset.id,label:asset.name,slideshowAssetIds:undefined,slideshowImageDuration:undefined,slideshowMotion:undefined});setReplaceId('');setPickerLane(null);setMessage('Asset an gleicher Position ersetzt.');return}
    const base=lane==='headline'||lane==='banner'?4:lane==='wan'&&imageLike(asset)?4:lane==='sound'?15:10;
    const clip:TimelineClip={id:uid('clip'),lane,assetId:asset.id,label:asset.name,start:nextStart(lane),duration:base,template:lane==='wan'?'broll':undefined,animation:['headline','banner'].includes(lane)?'news':undefined,caption:asset.caption||'',scale:1,rotation:0,volume:1};
    setTimeline(items=>[...items,clip]);setSelected(clip.id);setPickerLane(null);
    void probe(asset).then(d=>{if(d>0&&['main','wan','sound'].includes(lane))patch(clip.id,{duration:Math.min(d,60)})});
  }
  function addText(){const clip:TimelineClip={id:uid('text'),lane:'text',label:'Textfeld',text:textValue||'Textfeld',start:0,duration:Math.min(12,duration),x:540,y:1460,animation:'fade',scale:1,textStyle,textAlign};setTimeline(items=>[...items,clip]);setSelected(clip.id);setTextModal(false)}
  function buildSlideshow(ids:string[]){const unique=ids.filter(id=>assets.some(a=>a.id===id&&imageLike(a)));if(!unique.length){setMessage('Bitte zuerst Bilder für die News-Slideshow markieren.');return}const sequence=slideMotion==='news'?newsSequence(unique):unique;const clip:TimelineClip={id:uid('slide'),lane:'wan',label:slideMotion==='news'?`News-Slideshow ${unique.length} Bilder → ${sequence.length} Szenen`:`Slideshow ${unique.length} Bilder`,start:nextStart('wan'),duration:slideDuration,template:'broll',caption:'KI generiert',slideshowAssetIds:sequence,slideshowImageDuration:clamp(imageDuration,1,12),slideshowMotion:slideMotion,slideshowSourceCount:unique.length};setTimeline(items=>[...items,clip]);setSelected(clip.id);setSlideSelection(new Set());setPickerLane(null);setMessage(`News-Slideshow optimiert: ${unique.length} Bilder verarbeitet.`)}
  function regenerate(clip:TimelineClip){const source=[...new Set(clip.slideshowAssetIds||[])];if(!source.length)return;const sequence=newsSequence(shuffled(source));patch(clip.id,{slideshowAssetIds:sequence,label:`News-Slideshow ${source.length} Bilder → ${sequence.length} Szenen`,slideshowMotion:'news'});setMessage(`News-Slideshow neu generiert: ${source.length} Bilder neu gemischt.`)}

  function ensureMedia(asset:ProjectAsset){const cached=mediaRef.current.get(asset.id);if(cached)return cached;if(asset.kind==='video'){const v=document.createElement('video');v.src=asset.url;v.muted=true;v.playsInline=true;v.preload='auto';mediaRef.current.set(asset.id,v);return v}if(asset.kind==='audio'){const a=new Audio(asset.url);a.preload='auto';mediaRef.current.set(asset.id,a);return a}const img=new Image();img.src=asset.url;mediaRef.current.set(asset.id,img);return img}
  useEffect(()=>{assets.forEach(ensureMedia)},[project.assets,version]);
  function drawable(m:HTMLImageElement|HTMLVideoElement|HTMLAudioElement):m is HTMLImageElement|HTMLVideoElement{return m instanceof HTMLImageElement?m.complete:m instanceof HTMLVideoElement&&m.readyState>=2}
  function drawCover(ctx:CanvasRenderingContext2D,m:HTMLImageElement|HTMLVideoElement,x:number,y:number,w:number,h:number,scale=1){const mw=m instanceof HTMLImageElement?m.naturalWidth:m.videoWidth,mh=m instanceof HTMLImageElement?m.naturalHeight:m.videoHeight;if(!mw||!mh)return;const r=Math.max(w/mw,h/mh)*scale,dw=mw*r,dh=mh*r;ctx.drawImage(m,x+(w-dw)/2,y+(h-dh)/2,dw,dh)}
  function drawContain(ctx:CanvasRenderingContext2D,m:HTMLImageElement|HTMLVideoElement,x:number,y:number,w:number,h:number,scale=1,rotation=0,alpha=1){const mw=m instanceof HTMLImageElement?m.naturalWidth:m.videoWidth,mh=m instanceof HTMLImageElement?m.naturalHeight:m.videoHeight;if(!mw||!mh)return;const r=Math.min(w/mw,h/mh)*scale,dw=mw*r,dh=mh*r;ctx.save();ctx.globalAlpha=alpha;ctx.translate(x+w/2,y+h/2);ctx.rotate(rotation*Math.PI/180);ctx.drawImage(m,-dw/2,-dh/2,dw,dh);ctx.restore()}
  const active=(lane:TimelineLane,at:number)=>clips.filter(c=>c.lane===lane&&at>=c.start&&at<c.start+c.duration).sort((a,b)=>a.start-b.start).at(-1);
  function animation(clip:TimelineClip,at:number){const p=clamp((at-clip.start)/Math.min(.6,Math.max(.2,clip.duration*.18)),0,1);let alpha=1,scale=clip.scale||1,rotation=clip.rotation||0,dx=0,dy=0;if(clip.animation==='fade')alpha=p;if(clip.animation==='news'){dx=(1-p)*180;scale*=.82+.18*p}if(clip.animation==='left')rotation+=-16*(1-p);if(clip.animation==='right')rotation+=16*(1-p);if(clip.animation==='punch')scale*=.72+.28*p;if(clip.animation==='drop')dy=-220*(1-p);return{alpha,scale,rotation,dx,dy}}
  function slideshowAsset(clip:TimelineClip,at:number){const ids=clip.slideshowAssetIds||[];if(!ids.length)return;const local=Math.max(0,at-clip.start),index=Math.floor(local/Math.max(.5,clip.slideshowImageDuration||3.2))%ids.length;return assetMap.get(ids[index])}
  function renderFrame(at:number){
    const canvas=canvasRef.current;if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;ctx.fillStyle='#06090f';ctx.fillRect(0,0,W,H);
    const main=active('main',at);if(main?.assetId){const a=assetMap.get(main.assetId);if(a){const m=ensureMedia(a);if(m instanceof HTMLVideoElement){const local=clamp(at-main.start,0,Math.max(0,m.duration||main.duration));if(Math.abs(m.currentTime-local)>.15)try{m.currentTime=local}catch{}}if(drawable(m))drawCover(ctx,m,0,0,W,H,main.scale||1)}}
    const wan=active('wan',at);if(wan){const a=wan.slideshowAssetIds?.length?slideshowAsset(wan,at):(wan.assetId?assetMap.get(wan.assetId):undefined);if(a){const m=ensureMedia(a);if(drawable(m)){const local=(at-wan.start)/Math.max(.5,wan.slideshowImageDuration||3.2);let scale=wan.scale||1;if(wan.slideshowAssetIds?.length&&wan.slideshowMotion==='news')scale*=1.02+(.07*(local%1));if((wan.template||'broll')==='broll')drawCover(ctx,m,0,0,W,H,scale);else if(wan.template==='split'){ctx.save();ctx.beginPath();ctx.rect(0,H/2,W,H/2);ctx.clip();drawCover(ctx,m,0,H/2,W,H/2,scale);ctx.restore()}else{ctx.save();ctx.beginPath();ctx.roundRect(90,360,900,1120,42);ctx.clip();drawCover(ctx,m,90,360,900,1120,scale);ctx.restore()}}}}
    const headline=active('headline',at);if(headline?.assetId){const a=assetMap.get(headline.assetId);if(a){const m=ensureMedia(a);if(drawable(m)){const e=animation(headline,at);drawContain(ctx,m,50+e.dx,300+e.dy,980,1180,e.scale,e.rotation,e.alpha)}}}
    const banner=active('banner',at);if(banner?.assetId){const a=assetMap.get(banner.assetId);if(a){const m=ensureMedia(a);if(drawable(m)){const e=animation(banner,at);drawContain(ctx,m,60+e.dx,80+e.dy,960,420,e.scale,e.rotation,e.alpha)}}}
    const text=active('text',at);if(text?.text){const e=animation(text,at);ctx.save();ctx.globalAlpha=e.alpha;ctx.textAlign=text.textAlign||'center';ctx.font=`900 ${Math.round(58*(text.scale||1))}px Arial`;const lines=wrap(ctx,text.text,920),bh=lines.length*70+36;const red=text.textStyle==='redwhite';ctx.fillStyle=red?'rgba(190,0,20,.92)':text.textStyle==='white'?'rgba(255,255,255,.94)':'rgba(0,0,0,.7)';ctx.fillRect(50,(text.y||1460)-bh/2,980,bh);ctx.fillStyle=red||text.textStyle==='dark'?'#fff':'#111827';const tx=(text.textAlign||'center')==='left'?80:(text.textAlign||'center')==='right'?1000:540;lines.forEach((line,i)=>ctx.fillText(line,tx,(text.y||1460)-((lines.length-1)*35)+i*70));ctx.restore()}
    if(!clips.length){ctx.fillStyle='#94a3b8';ctx.font='700 42px Arial';ctx.textAlign='center';ctx.fillText(`${version.toUpperCase()} · Timeline ist leer`,W/2,H/2)}
  }
  useEffect(()=>{renderFrame(time)},[time,clips,project.assets]);
  useEffect(()=>{if(!playing){cancelAnimationFrame(rafRef.current);return}const base=performance.now()-time*1000;const tick=(now:number)=>{const next=(now-base)/1000;if(next>=duration){setTime(duration);setPlaying(false);return}setTime(next);rafRef.current=requestAnimationFrame(tick)};rafRef.current=requestAnimationFrame(tick);return()=>cancelAnimationFrame(rafRef.current)},[playing,duration]);
  useEffect(()=>{const sounds=clips.filter(c=>c.lane==='sound'&&c.assetId);for(const c of sounds){const a=c.assetId?assetMap.get(c.assetId):undefined;if(!a)continue;const m=ensureMedia(a);if(!(m instanceof HTMLAudioElement))continue;const on=time>=c.start&&time<c.start+c.duration;if(playing&&on){m.volume=clamp(c.volume??1,0,1);const local=time-c.start;if(Math.abs(m.currentTime-local)>.4)m.currentTime=local;void m.play().catch(()=>{})}else m.pause()}return()=>sounds.forEach(c=>{const m=c.assetId?mediaRef.current.get(c.assetId):undefined;if(m instanceof HTMLAudioElement)m.pause()})},[time,playing,clips,assetMap]);
  useEffect(()=>{const move=(e:PointerEvent)=>{const d=dragRef.current;if(!d)return;const delta=(e.clientX-d.x)/pxPerSec;if(d.mode==='move')patch(d.id,{start:Math.max(0,d.start+delta)});else if(d.mode==='left'){const end=d.start+d.duration,next=Math.min(end-.5,Math.max(0,d.start+delta));patch(d.id,{start:next,duration:end-next})}else patch(d.id,{duration:Math.max(.5,d.duration+delta)})};const up=()=>{dragRef.current=null};window.addEventListener('pointermove',move);window.addEventListener('pointerup',up);return()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',up)}},[pxPerSec]);
  function startDrag(e:ReactPointerEvent,clip:TimelineClip,mode:'move'|'left'|'right'){e.preventDefault();e.stopPropagation();setSelected(clip.id);setMenuPopover('');dragRef.current={id:clip.id,mode,x:e.clientX,start:clip.start,duration:clip.duration}}

  async function exportVideo(){if(exporting||!clips.length)return;const canvas=canvasRef.current;if(!canvas)return;setExporting(true);setMessage('Export läuft in Echtzeit …');setPlaying(false);try{const videoStream=canvas.captureStream(30);const audioCtx=new AudioContext({sampleRate:48000});const dest=audioCtx.createMediaStreamDestination();const sounds=clips.filter(c=>c.lane==='sound'&&c.assetId);const clones:{clip:TimelineClip;audio:HTMLAudioElement}[]=[];for(const c of sounds){const a=c.assetId?assetMap.get(c.assetId):undefined;if(!a)continue;const audio=new Audio(a.url);audio.crossOrigin='anonymous';await new Promise<void>(r=>{audio.onloadedmetadata=()=>r();audio.onerror=()=>r();setTimeout(r,800)});try{const node=audioCtx.createMediaElementSource(audio);node.connect(dest);clones.push({clip:c,audio})}catch{}}dest.stream.getAudioTracks().forEach(t=>videoStream.addTrack(t));await audioCtx.resume();const mime=MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm';const rec=new MediaRecorder(videoStream,{mimeType:mime,videoBitsPerSecond:8_000_000});const chunks:Blob[]=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const done=new Promise<void>(r=>{rec.onstop=()=>r()});rec.start(500);const start=performance.now();await new Promise<void>(resolve=>{const tick=(now:number)=>{const t=Math.min(duration,(now-start)/1000);setTime(t);renderFrame(t);for(const item of clones){const on=t>=item.clip.start&&t<item.clip.start+item.clip.duration;if(on){const local=t-item.clip.start;if(Math.abs(item.audio.currentTime-local)>.35)item.audio.currentTime=local;item.audio.volume=clamp(item.clip.volume??1,0,1);if(item.audio.paused)void item.audio.play().catch(()=>{})}else item.audio.pause()}if(t>=duration){resolve();return}requestAnimationFrame(tick)};requestAnimationFrame(tick)});rec.stop();await done;clones.forEach(x=>x.audio.pause());void audioCtx.close();const blob=new Blob(chunks,{type:'video/webm'}),url=URL.createObjectURL(blob),name=`studio-${version}-${Date.now()}.webm`;setProject(cur=>({...cur,assets:[{id:uid('export'),kind:'export',name,url,mime:'video/webm',size:blob.size,source:'studio-export',version},...cur.assets]}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setMessage('Export fertig und als Asset gespeichert.')}catch(e){setMessage(e instanceof Error?e.message:'Export fehlgeschlagen.')}finally{setExporting(false)}}

  const pickerAssets=pickerLane?assets.filter(a=>compatible(a,pickerLane)):[];
  const slideshowEligible=assets.filter(imageLike);
  const selectedLaneIndex=selectedClip?lanes.indexOf(selectedClip.lane):-1;
  const menuLeft=selectedClip?86+selectedClip.start*pxPerSec:86;
  const menuTop=selectedLaneIndex>=0?30+selectedLaneIndex*32:30;

  return <div className="studio-original">
    <div className="studio-original-top"><div className="version-context"><b>{version.toUpperCase()}</b><span>Eigene Timeline · passende Versions-Assets</span></div><div><button onClick={()=>{setTime(0);setPlaying(false)}}><RotateCcw size={14}/>Zurück</button><button className="primary" disabled={exporting||!clips.length} onClick={()=>void exportVideo()}><Download size={14}/>{exporting?'Export …':'Export'}</button></div></div>
    <div className="studio-original-main">
      <div className="studio-original-preview"><div className="studio-original-phone"><canvas ref={canvasRef} width={W} height={H}/><span>{fmt(time)} / {fmt(duration)}</span><button onClick={()=>setPlaying(p=>!p)}>{playing?<Pause size={21}/>:<Play size={21}/>}</button></div>{message&&<small className="studio-original-message">{message}</small>}</div>
      <div className="studio-original-assets"><div className="studio-original-assets-head"><b>Assets</b><select value={selectedClip?.template||'broll'} onChange={e=>selectedClip&&['main','wan'].includes(selectedClip.lane)&&patch(selectedClip.id,{template:e.target.value as ClipTemplate})}><option value="broll">B-Roll Fokus</option><option value="split">Split Fokus</option><option value="story">Story Window</option></select></div><div className="studio-mini-gallery"><button onClick={()=>assetStripRef.current?.scrollBy({left:-500,behavior:'smooth'})}>‹</button><div ref={assetStripRef} className="studio-mini-strip">{assets.map(asset=><div key={asset.id} className="studio-mini-asset" draggable onDragStart={e=>{e.dataTransfer.setData('application/asset',asset.id);e.dataTransfer.effectAllowed='copy'}} onDoubleClick={()=>addAsset(asset.kind==='audio'?'sound':asset.kind==='headline'?'headline':asset.kind==='banner'?'banner':'wan',asset)}>{asset.kind==='video'?<video src={asset.url} muted/>:asset.kind==='audio'?<span className="studio-audio-mark">♪</span>:<img src={asset.url} alt=""/>}<em>{asset.kind==='video'?'Video':asset.kind==='audio'?'Audio':'Bild'}</em></div>)}</div><button onClick={()=>assetStripRef.current?.scrollBy({left:500,behavior:'smooth'})}>›</button></div></div>
    </div>
    <div className="studio-original-timeline">
      <div className="studio-timeline-toolbar"><div><button onClick={()=>setZoom(z=>clamp(z-.25,.5,3))}>−</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>clamp(z+.25,.5,3))}>+</button></div><span>{fmt(time)} / {fmt(duration)}</span></div>
      <div className="studio-timeline-scroll">
        <div className="studio-timeline-content" style={{width:timelineWidth}} onPointerDown={e=>{const r=e.currentTarget.getBoundingClientRect();setTime(clamp((e.clientX-r.left-86)/pxPerSec,0,duration))}}>
          <div className="studio-ruler">{Array.from({length:Math.ceil(duration/5)+1},(_,i)=>i*5).map(mark=><span key={mark} style={{left:86+mark*pxPerSec}}>{mark}s</span>)}</div><div className="studio-playhead" style={{left:86+time*pxPerSec}}/>
          {selectedClip&&<div className="studio-clip-menu" style={{left:menuLeft,top:menuTop}} onPointerDown={e=>e.stopPropagation()}><button onClick={()=>{setReplaceId(selectedClip.id);setPickerLane(selectedClip.lane)}}>⇄ Ersetzen</button><button onClick={()=>duplicate(selectedClip)}>⧉ Kopie</button>{selectedClip.lane==='text'&&<button onClick={()=>{setTextValue(selectedClip.text||'');setTextStyle(selectedClip.textStyle||'redwhite');setTextAlign(selectedClip.textAlign||'center');setTextModal(true)}}>✎ Bearbeiten</button>}{selectedClip.slideshowAssetIds?.length&&<button onClick={()=>regenerate(selectedClip)}>↭ Mischen</button>}{['wan','main'].includes(selectedClip.lane)&&<button onClick={()=>setMenuPopover(menuPopover==='focus'?'':'focus')}>▣ Fokus</button>}{['headline','banner','text'].includes(selectedClip.lane)&&<button onClick={()=>setMenuPopover(menuPopover==='animation'?'':'animation')}>✦ Animation</button>}<button className="danger" onClick={()=>remove(selectedClip.id)}>⌫ Löschen</button>{menuPopover==='focus'&&<div className="studio-menu-popover focus">{(['broll','split','story'] as ClipTemplate[]).map(t=><button key={t} className={selectedClip.template===t?'active':''} onClick={()=>{patch(selectedClip.id,{template:t});setMenuPopover('')}}>{t==='broll'?'▰ B-Roll':t==='split'?'◫ Split':'▯ Story'}</button>)}</div>}{menuPopover==='animation'&&<div className="studio-menu-popover animation">{(Object.keys(animationLabels) as ClipAnimation[]).map(a=><button key={a} className={selectedClip.animation===a?'active':''} onClick={()=>{patch(selectedClip.id,{animation:a});setMenuPopover('')}}>{animationLabels[a]}</button>)}</div>}</div>}
          {lanes.map(lane=><div className="studio-lane-row" key={lane}><div className="studio-lane-name"><button onClick={()=>{if(lane==='text'){setTextSource(version);setTextValue(project.newsPackage?.versions[version]?.header||'');setTextModal(true)}else{setReplaceId('');setPickerLane(lane)}}}><Plus size={12}/></button><span>{laneLabels[lane]}</span></div><div className="studio-lane-track" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('application/asset'),a=assets.find(x=>x.id===id);if(a)addAsset(lane,a)}}>{clips.filter(c=>c.lane===lane).map(clip=><div key={clip.id} className={`studio-timeline-clip lane-${lane} ${selected===clip.id?'active':''}`} style={{left:clip.start*pxPerSec,width:Math.max(24,clip.duration*pxPerSec)}} onPointerDown={e=>startDrag(e,clip,'move')} onClick={e=>{e.stopPropagation();setSelected(clip.id);setTime(clip.start);setMenuPopover('')}}>{clip.slideshowAssetIds?.length?<div className="studio-thumb-strip">{clip.slideshowAssetIds.slice(0,10).map((id,i)=>{const a=assetMap.get(id);return <span key={`${id}-${i}`} style={a?{backgroundImage:`url(${a.url})`}:undefined}/>})}</div>:clip.assetId&&assetMap.get(clip.assetId)&&imageLike(assetMap.get(clip.assetId)!)?<span className="studio-clip-thumb" style={{backgroundImage:`url(${assetMap.get(clip.assetId)!.url})`}}/>:null}<span className="studio-resize left" onPointerDown={e=>startDrag(e,clip,'left')}/><b>{clip.label}</b><span className="studio-resize right" onPointerDown={e=>startDrag(e,clip,'right')}/></div>)}</div></div>)}
        </div>
      </div>
    </div>
    {pickerLane&&<div className="studio-modal-backdrop" onMouseDown={()=>{setPickerLane(null);setReplaceId('')}}><div className="studio-picker-modal" onMouseDown={e=>e.stopPropagation()}><header><div><b>{pickerLane==='wan'?'B-Roll auswählen':`${laneLabels[pickerLane]} auswählen`}</b><small>{replaceId?'Ausgewähltes Asset an gleicher Position ersetzen':'Passende Assets für diese Spur'}</small></div><button onClick={()=>{setPickerLane(null);setReplaceId('')}}><X size={18}/></button></header>{pickerLane==='wan'&&!replaceId&&<div className="studio-slideshow-tools"><button className="studio-news-optimize" onClick={()=>buildSlideshow(slideSelection.size?[...slideSelection]:slideshowEligible.map(a=>a.id))}>🎬 News-Slideshow optimieren</button><details><summary>⚙ Slideshow-Einstellungen</summary><div><label>Gesamtlänge<input type="number" min={10} max={1800} value={slideDuration} onChange={e=>setSlideDuration(clamp(Number(e.target.value)||80,10,1800))}/></label><label>Bilddauer<input type="number" min={1} max={12} step={.1} value={imageDuration} onChange={e=>setImageDuration(clamp(Number(e.target.value)||3.2,1,12))}/></label><label>Motion<select value={slideMotion} onChange={e=>setSlideMotion(e.target.value as SlideshowMotion)}>{motions.map(m=><option key={m} value={m}>{motionLabels[m]}</option>)}</select></label></div></details></div>}<div className="studio-picker-grid">{pickerAssets.map(asset=>{const marked=slideSelection.has(asset.id);return <button key={asset.id} className={marked?'marked':''} onClick={()=>addAsset(pickerLane,asset,replaceId)}>{asset.kind==='video'?<video src={asset.url} muted/>:asset.kind==='audio'?<span className="studio-audio-mark">♪</span>:<img src={asset.url} alt=""/>}<strong>{asset.name}</strong><small>{asset.kind==='video'?'Video · B-Roll':pickerLane==='wan'&&imageLike(asset)?'Antippen: einzelnes Bild':'Antippen zum Einfügen'}</small>{pickerLane==='wan'&&!replaceId&&imageLike(asset)&&<span className="studio-slide-pick" onClick={e=>{e.stopPropagation();setSlideSelection(cur=>{const next=new Set(cur);if(next.has(asset.id))next.delete(asset.id);else next.add(asset.id);return next})}}>{marked?'✓':'+'}</span>}</button>})}</div><footer><label className="studio-upload-btn">＋ Eigene Datei hinzufügen<input hidden type="file" accept={pickerLane==='sound'?'audio/*':pickerLane==='main'?'video/*':'image/*,video/*'} onChange={e=>{const f=e.target.files?.[0];if(!f)return;const kind=f.type.startsWith('video')?'video':f.type.startsWith('audio')?'audio':'image';const a:ProjectAsset={id:uid('asset'),kind,name:f.name,url:URL.createObjectURL(f),mime:f.type,size:f.size,source:'studio-upload',version};setProject(cur=>({...cur,assets:[a,...cur.assets]}));setTimeout(()=>addAsset(pickerLane,a,replaceId),0)}}/></label><button onClick={()=>{setPickerLane(null);setReplaceId('')}}>Fertig</button></footer></div></div>}
    {textModal&&<div className="studio-modal-backdrop" onMouseDown={()=>setTextModal(false)}><div className="studio-text-modal" onMouseDown={e=>e.stopPropagation()}><header><b>Textfeld einfügen</b><button onClick={()=>setTextModal(false)}><X size={18}/></button></header><label>Newspaket-Überschrift<select value={textSource} onChange={e=>{const key=e.target.value as VersionKey;setTextSource(key);setTextValue(project.newsPackage?.versions[key]?.header||'')}}>{versions.map((v,i)=><option value={v} key={v}>Version {i+1} · {project.newsPackage?.versions[v]?.header||''}</option>)}</select></label><label>Eigener Text<textarea value={textValue} onChange={e=>setTextValue(e.target.value)}/></label><div className="studio-text-options"><label>Stil<select value={textStyle} onChange={e=>setTextStyle(e.target.value as TextStyle)}><option value="redwhite">Rot / Weiß</option><option value="white">Weiß</option><option value="dark">Dunkel</option></select></label><label>Ausrichtung<select value={textAlign} onChange={e=>setTextAlign(e.target.value as TextAlign)}><option value="center">Zentriert</option><option value="left">Links</option><option value="right">Rechts</option></select></label></div><footer><button onClick={()=>setTextModal(false)}>Abbrechen</button><button className="primary" onClick={addText}>Als Textfeld einfügen</button></footer></div></div>}
  </div>;
}
